### ISSUE TITLE
background-size:cover

### ISSUE THREAD

**Issue by davidmarsprof** [Lmazenc34070/Unserious_game#2]
Sur un grand écran (plus grand que 1920/1080) ton background prend pas toute la page.
Tu trouveras ce qu'il te faut ici : 

- https://developer.mozilla.org/fr/docs/Web/CSS/background-size

- https://developer.mozilla.org/fr/docs/Web/CSS/background-position

**Comment by Lmazenc34070** [comment]
Merci de l'information, je pense avoir corrigé le problème en utilisant un "Background-size: cover;".
